name: Build and Push to ECR

on:
  push:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 814724283180.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t mediplus:${{github.run_number}} .
          docker tag mediplus:${{github.run_number}} 814724283180.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{github.run_number}}
          docker push 814724283180.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{github.run_number}}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-push
  #   steps:
  #     - name: Check my ssh key
  #       run: |
  #         echo "${{ secrets.SSH_KEY }}" > mykey.pem
  #         chmod 600 mykey.pem
  #         cat mykey.pem 
  #         ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@13.49.41.50 "docker pull 814724283180.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{github.run_number}}"
  #         # ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@13.49.41.50 "docker rm -f mediplux"
  #         ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@13.49.41.50 "docker run -d --name mediplux -p 80:80 814724283180.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{github.run_number}}"
    
        