# name: Build and Push to ECR

# on:
#   push:
#     branches:
#       - main
# jobs:
#   build-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-north-1

#       - name: Login to Amazon ECR
#         run: |
#           aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 814724283180.dkr.ecr.eu-north-1.amazonaws.com

#       - name: Build, tag, and push image to Amazon ECR
#         run: |
#           docker build -t mediplus:${{github.run_number}} .
#           docker tag mediplus:${{github.run_number}} 814724283180.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{github.run_number}}
#           docker push 814724283180.dkr.ecr.eu-north-1.amazonaws.com/mediplus:${{github.run_number}}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Check my ssh.key
        run: |
          echo "${{ secrets.SSH_KEY }}" > my-key.pem
          chmod 600 my-key.pem
          cat my-key.pem
          # ssh -i ssh.key -o StrictHostKeyChecking=no -i my-key ubuntu@13.49.41.50
        